### ISSUE TITLE
Byte Sequence Information types should denote the signature encoding

### ISSUE THREAD

**Issue by carlwilson** [openpreserve/par#29]
Wikidata supports an encoding property and holds examples for a few different encodings. A non-exhaustive sample is:

    Waveform Audio File signature "WAVE" encoding "ASCII"
    Waveform Audio File signature "57415645" encoding "hexadecimal"
    Windows Animated Cursor signature "ACON" encoding "ASCII"
    Geography Markup Language signature "3C3F786D6C2076657273696F6E3D22312E302220656E636F64696E673D22" encoding "hexadecimal"
    file shortcut signature "00021401-0000-0000-c000-000000000046" encoding "globally unique identifier"

**Comment by jhsimpson** [comment]
This change will increase the amount of data from wikiDP that can be viewed using https://github.com/openpreserve/par-wikidp , the reference implementation that was first supported in par 1.1.

**Comment by carlwilson** [comment]
Some thoughts here, Wikidata currently supports four different encodings:

- PRONOM internal signature
- ASCII
- hexadecimal
- Perl Compatible Regular Expressions 2

We have a couple of choices. One is to support encodings ourselves, which would mean a minor addition to the schema ByteSequence type, something like:

```
    ByteSequenceInformation:
      type: object
      properties:
        byteSequenceId:
          type: string
        byteSequenceIdNamespace:
          type: string
        byteSequenceValue:
          type: string
        encoding:
          type: string
        ...
```

Or, better still, some enumeration that restricts the values. We could take another approach, though. Instead of supporting different encodings, could we insist on hexadecimal encoding that complies with PRONOM sigs and convert errant values to hex? This might be easier to maintain in the long run but I'd have to write the code to convert. ASCII, hex and PRONOM (effectively what we already support) are all easy. Perl regexs might be the ones. For reference here's a count of the sig types:

| **SigType(( | **Count** |
|--------|--------|
| PRONOM | 41 |
| ASCII | 13 |
| hexadecimal | 9201 |
| Perl RegEx | 6 |

So not too many problem cases regardless, and the 6 PERL expressions are all similar variants. @jackdos and @jhsimpson thoughts welcomed :)
